services:
  - type: web
    name: trm-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn trm.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: False