services:
  - type: web
    name: trm-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn trm.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: trm-db
          property: connectionString

  - type: postgresql
    name: trm-db
    ipAllowList: []
    plan: free
    postgresMajorVersion: 16