services:
  - type: web
    name: trm-backend
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: trm-db
          property: connectionString
      - key: PORT
        value: 10000
    dependsOn:
      - trm-db

  - type: postgresql
    name: trm-db
    ipAllowList: []
    plan: free
    postgresMajorVersion: 16